import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrations1767796873408 implements MigrationInterface {
    name = 'Migrations1767796873408'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "meanings" DROP CONSTRAINT "meanings_id_words_fkey"`);
        await queryRunner.query(`ALTER TABLE "flashcards_sessions" DROP CONSTRAINT "flashcards_sessions_id_users_fkey"`);
        await queryRunner.query(`ALTER TABLE "flashcards_items" DROP CONSTRAINT "flashcards_items_id_repetitions_fkey"`);
        await queryRunner.query(`ALTER TABLE "flashcards_items" DROP CONSTRAINT "flashcards_items_id_sessions_fkey"`);
        await queryRunner.query(`ALTER TABLE "repetitions" DROP CONSTRAINT "repetitions_id_users_fkey"`);
        await queryRunner.query(`ALTER TABLE "repetitions" DROP CONSTRAINT "repetitions_id_words_fkey"`);
        await queryRunner.query(`ALTER TABLE "profiles" DROP CONSTRAINT "profiles_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "quizzes_sessions" DROP CONSTRAINT "quizzes_sessions_id_users_fkey"`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" DROP CONSTRAINT "quizzes_items_id_quizzes_packages_fkey"`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" DROP CONSTRAINT "quizzes_items_id_words_fkey"`);
        await queryRunner.query(`ALTER TABLE "quizzes_packages" DROP CONSTRAINT "quizzes_packages_id_quizzes_sessions_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_meanings_id_words"`);
        await queryRunner.query(`DROP INDEX "public"."idx_words_part_of_speech"`);
        await queryRunner.query(`DROP INDEX "public"."idx_words_word"`);
        await queryRunner.query(`DROP INDEX "public"."idx_words_level"`);
        await queryRunner.query(`DROP INDEX "public"."idx_flashcards_sessions_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_flashcards_sessions_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_flashcards_sessions_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_flashcards_sessions_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_flashcards_items_session"`);
        await queryRunner.query(`DROP INDEX "public"."idx_flashcards_items_repetition"`);
        await queryRunner.query(`DROP INDEX "public"."idx_flashcards_items_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_flashcards_items_stage"`);
        await queryRunner.query(`DROP INDEX "public"."idx_repetitions_user_next"`);
        await queryRunner.query(`DROP INDEX "public"."idx_repetitions_word_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_profiles_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_quizzes_sessions_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_quizzes_sessions_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_quizzes_sessions_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_quizzes_sessions_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_quizzes_items_package"`);
        await queryRunner.query(`DROP INDEX "public"."idx_quizzes_items_word"`);
        await queryRunner.query(`DROP INDEX "public"."idx_quizzes_packages_session"`);
        await queryRunner.query(`ALTER TABLE "words" DROP CONSTRAINT "words_level_check"`);
        await queryRunner.query(`ALTER TABLE "words" DROP CONSTRAINT "words_part_of_speech_check"`);
        await queryRunner.query(`ALTER TABLE "flashcards_sessions" DROP CONSTRAINT "flashcards_sessions_status_check"`);
        await queryRunner.query(`ALTER TABLE "flashcards_items" DROP CONSTRAINT "flashcards_items_status_check"`);
        await queryRunner.query(`ALTER TABLE "flashcards_items" DROP CONSTRAINT "flashcards_items_stage_check"`);
        await queryRunner.query(`ALTER TABLE "repetitions" DROP CONSTRAINT "repetitions_easiness_factor_check"`);
        await queryRunner.query(`ALTER TABLE "repetitions" DROP CONSTRAINT "repetitions_repetitions_check"`);
        await queryRunner.query(`ALTER TABLE "repetitions" DROP CONSTRAINT "repetitions_next_interval_check"`);
        await queryRunner.query(`ALTER TABLE "quizzes_sessions" DROP CONSTRAINT "quizzes_sessions_status_check"`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" DROP CONSTRAINT "quizzes_items_type_check"`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" DROP CONSTRAINT "quizzes_items_correct_answer_check"`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" DROP CONSTRAINT "quizzes_items_user_answer_check"`);
        await queryRunner.query(`ALTER TABLE "quizzes_packages" DROP CONSTRAINT "quizzes_packages_package_check"`);
        await queryRunner.query(`ALTER TABLE "quizzes_packages" DROP CONSTRAINT "quizzes_packages_level_check"`);
        await queryRunner.query(`ALTER TABLE "flashcards_items" DROP CONSTRAINT "unique_session_repetition"`);
        await queryRunner.query(`ALTER TABLE "repetitions" DROP CONSTRAINT "repetitions_id_users_id_words_key"`);
        await queryRunner.query(`ALTER TABLE "meanings" DROP COLUMN "meaning"`);
        await queryRunner.query(`ALTER TABLE "meanings" ADD "meaning" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "words" DROP COLUMN "level"`);
        await queryRunner.query(`ALTER TABLE "words" ADD "level" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "words" DROP CONSTRAINT "words_word_key"`);
        await queryRunner.query(`ALTER TABLE "words" DROP COLUMN "word"`);
        await queryRunner.query(`ALTER TABLE "words" ADD "word" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "words" ADD CONSTRAINT "UQ_38a98e41b6be0f379166dc2b58d" UNIQUE ("word")`);
        await queryRunner.query(`ALTER TABLE "words" DROP COLUMN "pronunciation"`);
        await queryRunner.query(`ALTER TABLE "words" ADD "pronunciation" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "words" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "flashcards_sessions" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "flashcards_items" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "flashcards_items" ADD "status" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "flashcards_items" DROP COLUMN "stage"`);
        await queryRunner.query(`ALTER TABLE "flashcards_items" ADD "stage" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "repetitions" DROP COLUMN "easiness_factor"`);
        await queryRunner.query(`ALTER TABLE "repetitions" ADD "easiness_factor" double precision NOT NULL DEFAULT '2.5'`);
        await queryRunner.query(`ALTER TABLE "repetitions" ALTER COLUMN "repetitions" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "repetitions" ALTER COLUMN "next_interval" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "profiles" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "profiles" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profiles" DROP COLUMN "surname"`);
        await queryRunner.query(`ALTER TABLE "profiles" ADD "surname" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profiles" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "profiles" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profiles" ADD CONSTRAINT "UQ_5b49bd22c967ce2829ca8f17720" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "profiles" DROP COLUMN "role"`);
        await queryRunner.query(`ALTER TABLE "profiles" ADD "role" character varying NOT NULL DEFAULT 'user'`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "daily_new_limit" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "daily_review_limit" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profiles" DROP COLUMN "learning_strategy"`);
        await queryRunner.query(`ALTER TABLE "profiles" ADD "learning_strategy" character varying NOT NULL DEFAULT 'random'`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" ADD "type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" DROP COLUMN "question"`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" ADD "question" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" DROP COLUMN "correct_answer"`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" ADD "correct_answer" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" DROP COLUMN "answer_a"`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" ADD "answer_a" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" DROP COLUMN "answer_b"`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" ADD "answer_b" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" DROP COLUMN "answer_c"`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" ADD "answer_c" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" DROP COLUMN "user_answer"`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" ADD "user_answer" character varying`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quizzes_packages" DROP COLUMN "package"`);
        await queryRunner.query(`ALTER TABLE "quizzes_packages" ADD "package" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quizzes_packages" DROP COLUMN "level"`);
        await queryRunner.query(`ALTER TABLE "quizzes_packages" ADD "level" character varying`);
        await queryRunner.query(`ALTER TABLE "quizzes_packages" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "meanings" ADD CONSTRAINT "FK_252d268539e9a7aa76274d59a11" FOREIGN KEY ("id_words") REFERENCES "words"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flashcards_sessions" ADD CONSTRAINT "FK_be5659d8f1a49fddc19b6cc93f7" FOREIGN KEY ("id_users") REFERENCES "profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flashcards_items" ADD CONSTRAINT "FK_fa60126fa0ed237ef71bdb1641d" FOREIGN KEY ("id_sessions") REFERENCES "flashcards_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flashcards_items" ADD CONSTRAINT "FK_1694588625d76cdfe64c01e8a0b" FOREIGN KEY ("id_repetitions") REFERENCES "repetitions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "repetitions" ADD CONSTRAINT "FK_29f9572a318480e416fbe17bfec" FOREIGN KEY ("id_users") REFERENCES "profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "repetitions" ADD CONSTRAINT "FK_353458bda5da559d77231996140" FOREIGN KEY ("id_words") REFERENCES "words"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quizzes_sessions" ADD CONSTRAINT "FK_a4d42cb3b4a967939ea8583edb2" FOREIGN KEY ("id_users") REFERENCES "profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" ADD CONSTRAINT "FK_5e3bacaa6fbb45330ed135c4547" FOREIGN KEY ("id_quizzes_packages") REFERENCES "quizzes_packages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" ADD CONSTRAINT "FK_0e86de83134c8c0f92479e9f0a9" FOREIGN KEY ("id_words") REFERENCES "words"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quizzes_packages" ADD CONSTRAINT "FK_b5b018a24122b281072424d28fb" FOREIGN KEY ("id_quizzes_sessions") REFERENCES "quizzes_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "quizzes_packages" DROP CONSTRAINT "FK_b5b018a24122b281072424d28fb"`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" DROP CONSTRAINT "FK_0e86de83134c8c0f92479e9f0a9"`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" DROP CONSTRAINT "FK_5e3bacaa6fbb45330ed135c4547"`);
        await queryRunner.query(`ALTER TABLE "quizzes_sessions" DROP CONSTRAINT "FK_a4d42cb3b4a967939ea8583edb2"`);
        await queryRunner.query(`ALTER TABLE "repetitions" DROP CONSTRAINT "FK_353458bda5da559d77231996140"`);
        await queryRunner.query(`ALTER TABLE "repetitions" DROP CONSTRAINT "FK_29f9572a318480e416fbe17bfec"`);
        await queryRunner.query(`ALTER TABLE "flashcards_items" DROP CONSTRAINT "FK_1694588625d76cdfe64c01e8a0b"`);
        await queryRunner.query(`ALTER TABLE "flashcards_items" DROP CONSTRAINT "FK_fa60126fa0ed237ef71bdb1641d"`);
        await queryRunner.query(`ALTER TABLE "flashcards_sessions" DROP CONSTRAINT "FK_be5659d8f1a49fddc19b6cc93f7"`);
        await queryRunner.query(`ALTER TABLE "meanings" DROP CONSTRAINT "FK_252d268539e9a7aa76274d59a11"`);
        await queryRunner.query(`ALTER TABLE "quizzes_packages" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quizzes_packages" DROP COLUMN "level"`);
        await queryRunner.query(`ALTER TABLE "quizzes_packages" ADD "level" text`);
        await queryRunner.query(`ALTER TABLE "quizzes_packages" DROP COLUMN "package"`);
        await queryRunner.query(`ALTER TABLE "quizzes_packages" ADD "package" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" DROP COLUMN "user_answer"`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" ADD "user_answer" text`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" DROP COLUMN "answer_c"`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" ADD "answer_c" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" DROP COLUMN "answer_b"`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" ADD "answer_b" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" DROP COLUMN "answer_a"`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" ADD "answer_a" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" DROP COLUMN "correct_answer"`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" ADD "correct_answer" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" DROP COLUMN "question"`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" ADD "question" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" ADD "type" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profiles" DROP COLUMN "learning_strategy"`);
        await queryRunner.query(`ALTER TABLE "profiles" ADD "learning_strategy" text NOT NULL DEFAULT 'random'`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "daily_review_limit" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "daily_new_limit" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profiles" DROP COLUMN "role"`);
        await queryRunner.query(`ALTER TABLE "profiles" ADD "role" text NOT NULL DEFAULT 'user'`);
        await queryRunner.query(`ALTER TABLE "profiles" DROP CONSTRAINT "UQ_5b49bd22c967ce2829ca8f17720"`);
        await queryRunner.query(`ALTER TABLE "profiles" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "profiles" ADD "email" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profiles" DROP COLUMN "surname"`);
        await queryRunner.query(`ALTER TABLE "profiles" ADD "surname" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profiles" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "profiles" ADD "name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "repetitions" ALTER COLUMN "next_interval" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "repetitions" ALTER COLUMN "repetitions" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "repetitions" DROP COLUMN "easiness_factor"`);
        await queryRunner.query(`ALTER TABLE "repetitions" ADD "easiness_factor" real DEFAULT 2.5`);
        await queryRunner.query(`ALTER TABLE "flashcards_items" DROP COLUMN "stage"`);
        await queryRunner.query(`ALTER TABLE "flashcards_items" ADD "stage" text NOT NULL DEFAULT 'review'`);
        await queryRunner.query(`ALTER TABLE "flashcards_items" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "flashcards_items" ADD "status" text NOT NULL DEFAULT 'review'`);
        await queryRunner.query(`ALTER TABLE "flashcards_sessions" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "words" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "words" DROP COLUMN "pronunciation"`);
        await queryRunner.query(`ALTER TABLE "words" ADD "pronunciation" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "words" DROP CONSTRAINT "UQ_38a98e41b6be0f379166dc2b58d"`);
        await queryRunner.query(`ALTER TABLE "words" DROP COLUMN "word"`);
        await queryRunner.query(`ALTER TABLE "words" ADD "word" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "words" ADD CONSTRAINT "words_word_key" UNIQUE ("word")`);
        await queryRunner.query(`ALTER TABLE "words" DROP COLUMN "level"`);
        await queryRunner.query(`ALTER TABLE "words" ADD "level" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "meanings" DROP COLUMN "meaning"`);
        await queryRunner.query(`ALTER TABLE "meanings" ADD "meaning" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "repetitions" ADD CONSTRAINT "repetitions_id_users_id_words_key" UNIQUE ("id_users", "id_words")`);
        await queryRunner.query(`ALTER TABLE "flashcards_items" ADD CONSTRAINT "unique_session_repetition" UNIQUE ("id_sessions", "id_repetitions")`);
        await queryRunner.query(`ALTER TABLE "quizzes_packages" ADD CONSTRAINT "quizzes_packages_level_check" CHECK ((level = ANY (ARRAY['A1-A2'::text, 'B1-B2'::text, 'C1-C2'::text])))`);
        await queryRunner.query(`ALTER TABLE "quizzes_packages" ADD CONSTRAINT "quizzes_packages_package_check" CHECK ((package = ANY (ARRAY['package-1'::text, 'package-2'::text, 'package-3'::text])))`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" ADD CONSTRAINT "quizzes_items_user_answer_check" CHECK ((user_answer = ANY (ARRAY['A'::text, 'B'::text, 'C'::text])))`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" ADD CONSTRAINT "quizzes_items_correct_answer_check" CHECK ((correct_answer = ANY (ARRAY['A'::text, 'B'::text, 'C'::text])))`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" ADD CONSTRAINT "quizzes_items_type_check" CHECK ((type = ANY (ARRAY['matching'::text, 'synonimOrAntonym'::text, 'clouze'::text])))`);
        await queryRunner.query(`ALTER TABLE "quizzes_sessions" ADD CONSTRAINT "quizzes_sessions_status_check" CHECK ((status = ANY (ARRAY['active'::text, 'completed'::text, 'abandoned'::text])))`);
        await queryRunner.query(`ALTER TABLE "repetitions" ADD CONSTRAINT "repetitions_next_interval_check" CHECK ((next_interval >= 0))`);
        await queryRunner.query(`ALTER TABLE "repetitions" ADD CONSTRAINT "repetitions_repetitions_check" CHECK ((repetitions >= 0))`);
        await queryRunner.query(`ALTER TABLE "repetitions" ADD CONSTRAINT "repetitions_easiness_factor_check" CHECK ((easiness_factor >= (1.3)::double precision))`);
        await queryRunner.query(`ALTER TABLE "flashcards_items" ADD CONSTRAINT "flashcards_items_stage_check" CHECK ((stage = ANY (ARRAY['review'::text, 'learning'::text, 'passed'::text])))`);
        await queryRunner.query(`ALTER TABLE "flashcards_items" ADD CONSTRAINT "flashcards_items_status_check" CHECK ((status = ANY (ARRAY['new'::text, 'review'::text])))`);
        await queryRunner.query(`ALTER TABLE "flashcards_sessions" ADD CONSTRAINT "flashcards_sessions_status_check" CHECK ((status = ANY (ARRAY['active'::text, 'completed'::text, 'abandoned'::text])))`);
        await queryRunner.query(`ALTER TABLE "words" ADD CONSTRAINT "words_part_of_speech_check" CHECK (((part_of_speech IS NULL) OR (part_of_speech <@ ARRAY['noun'::text, 'verb'::text, 'adjective'::text, 'adverb'::text, 'pronoun'::text, 'preposition'::text, 'conjunction'::text, 'interjection'::text])))`);
        await queryRunner.query(`ALTER TABLE "words" ADD CONSTRAINT "words_level_check" CHECK ((level = ANY (ARRAY['A1'::text, 'A2'::text, 'B1'::text, 'B2'::text, 'C1'::text, 'C2'::text])))`);
        await queryRunner.query(`CREATE INDEX "idx_quizzes_packages_session" ON "quizzes_packages" ("id_quizzes_sessions") `);
        await queryRunner.query(`CREATE INDEX "idx_quizzes_items_word" ON "quizzes_items" ("id_words") `);
        await queryRunner.query(`CREATE INDEX "idx_quizzes_items_package" ON "quizzes_items" ("id_quizzes_packages") `);
        await queryRunner.query(`CREATE INDEX "idx_quizzes_sessions_date" ON "quizzes_sessions" ("date_started") `);
        await queryRunner.query(`CREATE INDEX "idx_quizzes_sessions_type" ON "quizzes_sessions" ("type") `);
        await queryRunner.query(`CREATE INDEX "idx_quizzes_sessions_status" ON "quizzes_sessions" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_quizzes_sessions_user" ON "quizzes_sessions" ("id_users") `);
        await queryRunner.query(`CREATE INDEX "idx_profiles_email" ON "profiles" ("email") `);
        await queryRunner.query(`CREATE INDEX "idx_repetitions_word_user" ON "repetitions" ("id_users", "id_words") `);
        await queryRunner.query(`CREATE INDEX "idx_repetitions_user_next" ON "repetitions" ("date_next_rep", "id_users") `);
        await queryRunner.query(`CREATE INDEX "idx_flashcards_items_stage" ON "flashcards_items" ("stage") `);
        await queryRunner.query(`CREATE INDEX "idx_flashcards_items_status" ON "flashcards_items" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_flashcards_items_repetition" ON "flashcards_items" ("id_repetitions") `);
        await queryRunner.query(`CREATE INDEX "idx_flashcards_items_session" ON "flashcards_items" ("id_sessions") `);
        await queryRunner.query(`CREATE INDEX "idx_flashcards_sessions_type" ON "flashcards_sessions" ("type") `);
        await queryRunner.query(`CREATE INDEX "idx_flashcards_sessions_status" ON "flashcards_sessions" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_flashcards_sessions_user" ON "flashcards_sessions" ("id_users") `);
        await queryRunner.query(`CREATE INDEX "idx_flashcards_sessions_date" ON "flashcards_sessions" ("date_started") `);
        await queryRunner.query(`CREATE INDEX "idx_words_level" ON "words" ("level") `);
        await queryRunner.query(`CREATE INDEX "idx_words_word" ON "words" ("word") `);
        await queryRunner.query(`CREATE INDEX "idx_words_part_of_speech" ON "words" ("part_of_speech") `);
        await queryRunner.query(`CREATE INDEX "idx_meanings_id_words" ON "meanings" ("id_words") `);
        await queryRunner.query(`ALTER TABLE "quizzes_packages" ADD CONSTRAINT "quizzes_packages_id_quizzes_sessions_fkey" FOREIGN KEY ("id_quizzes_sessions") REFERENCES "quizzes_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" ADD CONSTRAINT "quizzes_items_id_words_fkey" FOREIGN KEY ("id_words") REFERENCES "words"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quizzes_items" ADD CONSTRAINT "quizzes_items_id_quizzes_packages_fkey" FOREIGN KEY ("id_quizzes_packages") REFERENCES "quizzes_packages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quizzes_sessions" ADD CONSTRAINT "quizzes_sessions_id_users_fkey" FOREIGN KEY ("id_users") REFERENCES "profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "profiles" ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "repetitions" ADD CONSTRAINT "repetitions_id_words_fkey" FOREIGN KEY ("id_words") REFERENCES "words"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "repetitions" ADD CONSTRAINT "repetitions_id_users_fkey" FOREIGN KEY ("id_users") REFERENCES "profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flashcards_items" ADD CONSTRAINT "flashcards_items_id_sessions_fkey" FOREIGN KEY ("id_sessions") REFERENCES "flashcards_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flashcards_items" ADD CONSTRAINT "flashcards_items_id_repetitions_fkey" FOREIGN KEY ("id_repetitions") REFERENCES "repetitions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flashcards_sessions" ADD CONSTRAINT "flashcards_sessions_id_users_fkey" FOREIGN KEY ("id_users") REFERENCES "profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meanings" ADD CONSTRAINT "meanings_id_words_fkey" FOREIGN KEY ("id_words") REFERENCES "words"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
